Filter reflected classes by class type instead of searching for '=> ' tags
viash-io/viash pull request #347
Opened 2023-01-26 15:33 UTC by Grifs

In Scala 2.12, the '=> ' tag was a reliable way to filter, but with Scala 2.13 this is no longer present. Filtering for "NullaryMethodType" instead gives the desired functionality now.

Improve the syntax of the mapping of a tuple and unapply to 2 names.

No changelog entry added as I consider it part of updating to Scala 2.13

2023-02-20 22:02 UTC, rcannood requested changes
Could you add an entry to the changelog

2023-02-21 06:58 UTC, Grifs commented
> Could you add an entry to the changelog

I considered this change a part of "`Scala`: Updated to Scala 2.13 and updated several dependencies." (or it should have been) from this release

2023-02-21 07:04 UTC, Grifs commented on src/main/scala/io/viash/schemas/CollectedSchemas.scala
> +           .filter(m => !m.info.getClass.toString.endsWith("NullaryMethodType") || index != 0) // Only regular members if base class, otherwise all members
Good catch!

2023-02-21 07:17 UTC, rcannood commented
> > Could you add an entry to the changelog
> 
> I considered this change a part of "`Scala`: Updated to Scala 2.13 and updated several dependencies." (or it should have been) from this release

Fair enough!

2023-02-21 07:17 UTC, merged