Hub/git attempt anonymous
viash-io/viash pull request #462
Opened 2023-06-27 09:24 UTC by Grifs

## Describe your changes

Attempt github clones in following order:
- HTTPS forced anonymous
- SSH key
- HTTPS with user supplied credentials

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [x] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] Relevant unit tests have been added

2023-06-28 09:39 UTC, rcannood commented
Is there something we can do in terms of unit testing?

2023-07-04 07:44 UTC, rcannood requested changes
Is there something we can do in terms of unit testing? :)

2023-07-04 07:51 UTC, Grifs commented
> Is there something we can do in terms of unit testing? :)

I'm open for suggestions

2023-07-07 07:36 UTC, rcannood approved these changes
Much butter! I could only find a minor typo :)

2023-07-07 07:36 UTC, rcannood commented on src/main/scala/io/viash/functionality/dependencies/GithubRepository.scala
> +  val fakeCredentials = "nouser:nopass@" // obfuscate the credentials a bit so we don't trigger GitGardian
```suggestion
  val fakeCredentials = "nouser:nopass@" // obfuscate the credentials a bit so we don't trigger GitGuardian
```

2023-07-07 07:36 UTC, rcannood commented on src/main/scala/io/viash/functionality/dependencies/ViashhubRepository.scala
> +  val fakeCredentials = "nouser:nopass@" // obfuscate the credentials a bit so we don't trigger GitGardian
```suggestion
  val fakeCredentials = "nouser:nopass@" // obfuscate the credentials a bit so we don't trigger GitGuardian
```

2023-07-07 07:39 UTC, merged