Fix: multiple: true for outputs including unit test
viash-io/viash pull request #639
Opened 2024-02-05 15:51 UTC by tverbeiren

## Describe your changes

## Related issue(s)

Closes #xxxx 

## Type of Change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New functionality (non-breaking change which adds functionality)
- [ ] Major change (non-breaking change which modifies existing functionality)
- [ ] Minor change (non-breaking change which does not modify existing functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist

Requirements:

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc.
- [x] I have performed a self-review of my code by checking the "Changed Files" tab.
- [x] My code follows the code style of this project.

Tests:

- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

Documentation:

- [ ] Proposed changes are described in the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.

## Test Environment

2024-02-09 10:00 UTC, rcannood approved these changes
LGTM

2024-02-09 11:51 UTC, rcannood requested changes
Wait!

2024-03-08 07:50 UTC, Grifs reviewed
all seems pretty reasonable. Found a minor indentation fault.

2024-03-08 07:50 UTC, Grifs commented on src/main/scala/io/viash/wrapper/BashWrapper.scala
> +                |fi""".stripMargin
```suggestion
              s"""if [ ! -z "$$${param.VIASH_PAR}" ] && [ ! -e "$$${param.VIASH_PAR}" ]; then
                 |  ViashError "$direction file '$$${param.VIASH_PAR}' does not exist."
                 |  exit 1
                 |fi""".stripMargin
```

2024-03-12 11:38 UTC, rcannood commented on src/main/scala/io/viash/wrapper/BashWrapper.scala
> +                |fi""".stripMargin
Thx!

2024-03-12 11:38 UTC, rcannood approved these changes

2024-03-15 08:01 UTC, rcannood commented on src/main/scala/io/viash/functionality/arguments/FileArgument.scala
> +      |'--foo=foo_*.txt' will be treated as a list of files that match the pattern.
```suggestion
      |For output file arguments, the passed value needs to contain a wildcard. For example,
      |`--foo 'foo_*.txt'` will be treated as a list of files that match the pattern. Note that in Bash,
      | the wildcard will need to be in quotes (`"foo_*.txt"` or `'foo_*.txt'`) or else Bash will
      | automatically attempt to expand the expression.
```

2024-03-15 08:02 UTC, tverbeiren commented on src/main/scala/io/viash/functionality/arguments/FileArgument.scala
> +      |'--foo=foo_*.txt' will be treated as a list of files that match the pattern.
+1

2024-03-15 08:03 UTC, tverbeiren commented
LGTM!

2024-03-15 09:09 UTC, merged