Make docker runargs configurable
viash-io/viash pull request #740
Opened 2024-07-10 05:02 UTC by rcannood

## Describe your changes

## Related issue(s)

Closes #xxxx 

## Type of Change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New functionality (non-breaking change which adds functionality)
- [ ] Major change (non-breaking change which modifies existing functionality)
- [ ] Minor change (non-breaking change which does not modify existing functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist

Requirements:

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc.
- [ ] I have performed a self-review of my code by checking the "Changed Files" tab.
- [ ] My code follows the code style of this project.

Tests:

- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

Documentation:

- [ ] Proposed changes are described in the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.

## Test Environment

2024-07-11 10:48 UTC, Grifs requested changes
minor change, isn't this what you probably meant to do?

2024-07-11 10:48 UTC, Grifs commented on src/main/scala/io/viash/runners/ExecutableRunner.scala
> +        """.stripMargin
```suggestion
        |""".stripMargin
```

2024-07-11 18:04 UTC, rcannood commented on src/main/scala/io/viash/runners/ExecutableRunner.scala
> +        |""".stripMargin
```suggestion
        |VIASH_DOCKER_RUN_ARGS=($dockerArgs)""".stripMargin
```

2024-07-15 12:40 UTC, Grifs approved these changes

2024-07-16 06:11 UTC, merged